version: 2

defaults: &defaults
  working_directory: ~/kontejnery/frontend

jobs:
  build:
    <<: *defaults
    docker:
    - image: circleci/node:8
    steps:
    - run: yarn install
    - run: yarn test

  deploy:
    <<: *defaults
    steps:
    - run:
      command: |
        NODE_ENV=production yarn run build
        aws s3 sync ./build s3://www.velkoobjemaky.cz/ --delete --region=eu-central-1 --acl=public-read
        aws configure set preview.cloudfront true
        aws cloudfront create-invalidation --distribution-id $AWS_DISTRIBUTION_ID --paths / /index.html
