version: 2
jobs:
  build:
    docker:
    - image: circleci/node:8
    steps:
    - checkout
    - working_directory: ~/frontend
    - run: yarn install
    - run: yarn test

  deploy:
    working_directory: ~/frontend
    docker:
    - image: circleci/node:8
    steps:
    - run:
      command: |
        NODE_ENV=production yarn run build
        aws s3 sync ./build s3://www.velkoobjemaky.cz/ --delete --region=eu-central-1 --acl=public-read
        aws configure set preview.cloudfront true
        aws cloudfront create-invalidation --distribution-id $AWS_DISTRIBUTION_ID --paths / /index.html
