"""empty message

Revision ID: 2a96052c0194
Revises: 
Create Date: 2016-11-27 23:08:50.858589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a96052c0194'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('containers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('datetime_from', sa.DateTime(), nullable=True),
    sa.Column('datetime_to', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_containers_position'), 'containers', ['position'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_containers_position'), table_name='containers')
    op.drop_table('containers')
    ### end Alembic commands ###
