"""empty message

Revision ID: 57b1d6fb5b9a
Revises: ee2aa0d04791
Create Date: 2017-04-09 15:14:46.711805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57b1d6fb5b9a'
down_revision = 'ee2aa0d04791'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('containers', sa.Column('created_at', sa.DateTime()))
    op.add_column('containers', sa.Column('updated_at', sa.DateTime()))
    op.add_column('terms', sa.Column('created_at', sa.DateTime()))
    op.add_column('terms', sa.Column('updated_at', sa.DateTime()))

    op.execute('UPDATE terms SET created_at = NOW(), updated_at= now()')
    op.execute('UPDATE containers SET created_at = NOW(), updated_at= now()')

    op.alter_column('containers', 'created_at', nullable=False)
    op.alter_column('containers', 'created_at', nullable=False)
    op.alter_column('terms', 'created_at', nullable=False)
    op.alter_column('terms', 'created_at', nullable=False)


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('terms', 'updated_at')
    op.drop_column('terms', 'created_at')
    op.drop_column('containers', 'updated_at')
    op.drop_column('containers', 'created_at')
    # ### end Alembic commands ###
